### ISSUE TITLE
Include multiplication reverse engineering?

### ISSUE THREAD

**Issue by ghost** [psx-spx/psx-spx.github.io#26]
Hello,

A while ago, I [reverse engineered][1] how multiplication inside of the MIPS CPU core works. This was done by issuing carefully timed writes to the `LO`/`HI` registers after starting the operation. I noticed that the ranges used to determine timing were different than what Martin had in his docs. I attempted to contact him directly but it was a giant pain, and I gave up on it. Since this should be easier, I'm just making it known that this exists and is 100% verified on my `SCPH-7501` and `SCPH-5501` consoles.

If there's interest, I can include a write-up of the `DIV`/`DIVU` operations as well.

[1]: https://gitlab.com/psxact/psxact/-/wikis/CPU/Multiplication

**Comment by nicolasnoble** [comment]
Totally feel free to issue pull requests with your findings :)
