### ISSUE TITLE
GP0(E2h) - Texture Window setting

### ISSUE THREAD

**Issue by EngineersBox** [psx-spx/psx-spx.github.io#67]
# Context

Hi,

I noticed on the docs that packet 0xe2 for texture windows is detailed as follows for caclulating the new texture coordinate based on the supplied parameters of x,y,w,h in units of 8 pixels:

```
0-4    Texture window Mask X   (in 8 pixel steps)
5-9    Texture window Mask Y   (in 8 pixel steps)
10-14  Texture window Offset X (in 8 pixel steps)
15-19  Texture window Offset Y (in 8 pixel steps)
20-23  Not used (zero)
24-31  Command  (E2h)

Texcoord = (Texcoord AND (NOT (Mask * 8))) OR ((Offset AND Mask) * 8)
```

The issue i see with this is that using `NOT (Mask * 8)` would produce an inversion mask that removes the bit selected by the mask. I.e. using a mask of 2 (equating to 16 pixels), would mean that `NOT (Mask * 8) = 0b1111111111101111` when in reality it should be `0b1111`.

# Example

Supposing we use `Mask = 0x2` and `Offset = 0x6` then vary `Texcoord` in the range `[0,48]` to emulate masking a 16 pixel width window over a 48 pixel UV space, we get the following (i've wrapped the lines at intervals of 16 for ease of viewing):

```c
16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
```

Which (in my understanding) does not make sense since we suddenly jump texture coords from 16-31 to 48-63 in the third wrapping interval. In stead I would expect the following:

```c
16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
```

Which ensures that the texture continually wraps.

# Solution

Instead of the current definition for `Texcoord` as above, the doc should read:
```
Texcoord = (Texcoord AND ((Mask * 8) - 1)) OR ((Offset AND Mask) * 8)
```

Which does accurately represent the expected wrapping.

# Conclusion

I wanted to check that this is indeed the case and I'm not missing something else, or the definition of logical `NOT` employed here is defined elsewhere that implies the correct wrapping.

**Comment by nicolasnoble** [comment]
Yeah you're actually right. Feel free to send a PR to fix this one.

**Comment by EngineersBox** [comment]
Great, thanks. I'll PR it.
